version: "3"

services:
  hello_oci_runner:
    container_name: hello_oci_runner
    image: interaction/github-actions-runner:latest
    restart: always
    env_file:
      - ./runner.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
