name: CI-CD
on: [push]

env:
  DOCKER_NAME: hello_oci
  DOCKER_IMAGE: ghcr.io/heavyrisem/hello_oci

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      # Checkout Repository
      - uses: actions/checkout@v2.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to ghcr
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build and Push
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.GITHUB_RUN_NUMBER }}
          platforms: linux/arm64

      # - name: Build Image
      #   run: docker buildx build --platform linux/arm64 -t ${{env.DOCKER_IMAGE}} .
